FROM apache/airflow:3.1.7-python3.12
USER root
RUN apt-get update && apt-get install -y --no-install-recommends openjdk-17-jre-headless && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /opt/airflow/lake && chown airflow:root /opt/airflow/lake
USER airflow
RUN pip install --no-cache-dir pyspark==4.0.2 boto3==1.40.50
COPY --chown=airflow:root pipeline /opt/airflow/pipeline
ENV PYTHONPATH=/opt/airflow SPARK_LOCAL_IP=127.0.0.1
